---
# List your controller-side system package and/or Python package requirements
# if exist in the files specified below to support easy execution environments building for your collection users
# https://ansible.readthedocs.io/en/latest/getting_started_ee/index.html
# If there are no such dependencies, please just remove the files.
# See https://ansible.readthedocs.io/projects/builder/en/latest/collection_metadata/#how-to-verify-collection-level-metadata
# to learn how to test your configuration.

version: 3
dependencies:
  python: meta/ee-requirements.txt
  system: meta/ee-bindep.txt
